[workspace]
authors = ["Mark Zhitomirski <marcuzero@gmail.com>"]
channels = ["conda-forge"]
name = "grab-a-pic"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
grab = "python grab.py"
list = "python grab.py --list"

[dependencies]
python = "3.14.*"
requests = ">=2.34.2,<3"
beautifulsoup4 = ">=4.14.3,<5"
lxml = ">=6.1.1,<7"
pillow = ">=12.2.0,<13"
